logging="INFO"
identity="bank"
data-path="/opt/besu/data"
genesis-file="/config/genesis.json"
node-private-key-file="/opt/besu/keys/key"
nat-method="DOCKER"
host-whitelist=["*"]

# P2P related

p2p-host="0.0.0.0"
p2p-port=30303

# RPC related

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8503
rpc-http-api=["ADMIN", "CLIQUE", "ETH", "NET", "TXPOOL", "WEB3"]
rpc-http-cors-origins=["*"]

